# Generated by Django 5.0 on 2024-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_destination_travelpartner_tripdetail_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripdetail',
            name='location',
        ),
        migrations.AddField(
            model_name='tripdetail',
            name='location',
            field=models.ManyToManyField(to='dashboard.destination'),
        ),
    ]
