# Generated by Django 5.0 on 2024-02-01 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_tripdetail_location_tripdetail_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripdetail',
            name='passengers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
