# Generated by Django 5.0 on 2024-02-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_cordinator_tripdetail_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelpartner',
            name='logoname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='travelpartner',
            name='partnerimage',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
