# Generated by Django 5.0 on 2024-02-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_travelpartner_logoname_travelpartner_partnerimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
