# Generated by Django 5.0 on 2024-02-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='garage',
            name='vehiclename',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
